import { INodeProperties } from 'n8n-workflow';

export const synthesisProperties: INodeProperties[] = [
	{
		displayName: 'テキスト: text',
		name: 'text',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				operation: ['synthesize', 'audioQuery'],
			},
		},
		description: '読み上げるテキスト',
	},
	{
		displayName: '話者ID: speakerId',
		name: 'speakerId',
		type: 'number',
		default: 888753760,
		required: true,
		displayOptions: {
			show: {
				operation: ['synthesize', 'audioQuery', 'synthesisFromQuery'],
			},
		},
		description: '話者のスタイルID（話者一覧取得で確認可能）',
	},
	{
		displayName: 'ベース話者ID: speakerId',
		name: 'speakerId',
		type: 'number',
		default: 888753760,
		required: true,
		displayOptions: {
			show: {
				operation: ['multiSynthesis'],
			},
		},
		description: 'ベースの話者スタイルID（個別設定がないテキストはこのIDを使用）',
	},
	{
		displayName: 'ベース音声設定: baseAudioParams',
		name: 'baseAudioParams',
		type: 'collection',
		default: {},
		placeholder: 'ベース設定を追加',
		displayOptions: {
			show: {
				operation: ['multiSynthesis'],
			},
		},
		description: '全テキスト共通のベース音声設定。個別設定がないテキストはこの値を使用',
		options: [
			{
				displayName: 'ベース話速: speedScale',
				name: 'speedScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.5, maxValue: 2.0, numberStepSize: 0.1 },
				description: 'ベースの話す速さ（最小: 0.5、最大: 2.0、デフォルト: 1.0）',
			},
			{
				displayName: 'ベース音高: pitchScale',
				name: 'pitchScale',
				type: 'number',
				default: 0.0,
				typeOptions: { minValue: -0.15, maxValue: 0.15, numberStepSize: 0.01 },
				description: 'ベースの声の高さ（最小: -0.15、最大: 0.15、デフォルト: 0.0）',
			},
			{
				displayName: 'ベース感情表現: intonationScale',
				name: 'intonationScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: 'ベースの感情表現の強弱（最小: 0.0、最大: 2.0、デフォルト: 1.0）。話者スタイルに応じた感情の込め方を調整',
			},
			{
				displayName: 'ベース音量: volumeScale',
				name: 'volumeScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: 'ベースの音量（最小: 0.0、最大: 2.0、デフォルト: 1.0）',
			},
			{
				displayName: 'ベース開始無音: prePhonemeLength',
				name: 'prePhonemeLength',
				type: 'number',
				default: 0.1,
				typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
				description: 'ベースの音声開始前の無音の長さ（最小: 0.0秒、最大: 1.5秒、デフォルト: 0.1秒）',
			},
			{
				displayName: 'ベース終了無音: postPhonemeLength',
				name: 'postPhonemeLength',
				type: 'number',
				default: 0.1,
				typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
				description: 'ベースの音声終了後の無音の長さ（最小: 0.0秒、最大: 1.5秒、デフォルト: 0.1秒）',
			},
			{
				displayName: 'ベース句読点無音: pauseLength',
				name: 'pauseLength',
				type: 'number',
				default: 0.0,
				typeOptions: { minValue: 0.0, maxValue: 3.0, numberStepSize: 0.1 },
				description: 'ベースの句読点などの無音時間（最小: 0.0秒、最大: 3.0秒）。未設定の場合はAPIデフォルト（null=自動）を使用',
			},
			{
				displayName: 'ベーステンポ緩急: tempoDynamicsScale',
				name: 'tempoDynamicsScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: 'ベースのテンポの緩急の強弱（最小: 0.0、最大: 2.0、デフォルト: 1.0）。AivisSpeech固有',
			},
		],
	},
	{
		displayName: 'バイナリプロパティ名: binaryPropertyName',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		displayOptions: {
			show: {
				operation: ['synthesize', 'synthesisFromQuery', 'multiSynthesis'],
			},
		},
		description: 'バイナリ出力のプロパティ名（後続ノードで $binary.この名前 で参照）',
	},
	// multiSynthesis 専用パラメータ
	{
		displayName: '入力方式: inputMode',
		name: 'inputMode',
		type: 'options',
		options: [
			{ name: 'GUI入力', value: 'gui' },
			{ name: 'JSON入力', value: 'json' },
		],
		default: 'gui',
		displayOptions: {
			show: {
				operation: ['multiSynthesis'],
			},
		},
		description: 'テキスト一覧の入力方式',
	},
	{
		displayName: 'テキスト一覧: texts',
		name: 'texts',
		type: 'fixedCollection',
		typeOptions: {
			multipleValues: true,
		},
		default: {},
		displayOptions: {
			show: {
				operation: ['multiSynthesis'],
				inputMode: ['gui'],
			},
		},
		description: '合成するテキストの一覧',
		options: [
			{
				displayName: 'テキスト',
				name: 'textItems',
				values: [
					{
						displayName: 'テキスト: text',
						name: 'text',
						type: 'string',
						default: '',
						required: true,
						description: '読み上げるテキスト',
					},
					{
						displayName: '個別設定: overrides',
						name: 'overrides',
						type: 'collection',
						default: {},
						placeholder: '個別設定を追加',
						options: [
							{
								displayName: '話者ID: speakerId',
								name: 'speakerId',
								type: 'number',
								default: 888753760,
								description: '個別の話者ID。未設定の場合はベースの話者IDを使用',
							},
							{
								displayName: '話速: speedScale',
								name: 'speedScale',
								type: 'number',
								default: 1.0,
								typeOptions: { minValue: 0.5, maxValue: 2.0, numberStepSize: 0.1 },
								description: '個別の話速（最小: 0.5、最大: 2.0）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '音高: pitchScale',
								name: 'pitchScale',
								type: 'number',
								default: 0.0,
								typeOptions: { minValue: -0.15, maxValue: 0.15, numberStepSize: 0.01 },
								description: '個別の音高（最小: -0.15、最大: 0.15）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '感情表現: intonationScale',
								name: 'intonationScale',
								type: 'number',
								default: 1.0,
								typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
								description: '個別の感情表現の強弱（最小: 0.0、最大: 2.0）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '音量: volumeScale',
								name: 'volumeScale',
								type: 'number',
								default: 1.0,
								typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
								description: '個別の音量（最小: 0.0、最大: 2.0）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '開始無音: prePhonemeLength',
								name: 'prePhonemeLength',
								type: 'number',
								default: 0.1,
								typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
								description: '個別の開始無音（最小: 0.0秒、最大: 1.5秒）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '終了無音: postPhonemeLength',
								name: 'postPhonemeLength',
								type: 'number',
								default: 0.1,
								typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
								description: '個別の終了無音（最小: 0.0秒、最大: 1.5秒）。未設定の場合はベースの値を使用',
							},
							{
								displayName: '句読点無音: pauseLength',
								name: 'pauseLength',
								type: 'number',
								default: 0.0,
								typeOptions: { minValue: 0.0, maxValue: 3.0, numberStepSize: 0.1 },
								description: '個別の句読点などの無音時間（最小: 0.0秒、最大: 3.0秒）。未設定の場合はベースの値を使用',
							},
							{
								displayName: 'テンポ緩急: tempoDynamicsScale',
								name: 'tempoDynamicsScale',
								type: 'number',
								default: 1.0,
								typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
								description: '個別のテンポの緩急（最小: 0.0、最大: 2.0）。未設定の場合はベースの値を使用',
							},
						],
					},
				],
			},
		],
	},
	{
		displayName: 'テキスト一覧 (JSON): textsJson',
		name: 'textsJson',
		type: 'json',
		default: '[\n  { "text": "テキスト1" },\n  { "text": "テキスト2", "speakerId": 888753760, "speedScale": 1.0, "pitchScale": 0.0, "intonationScale": 1.0, "volumeScale": 1.0, "prePhonemeLength": 0.1, "postPhonemeLength": 0.1, "pauseLength": 0.0, "tempoDynamicsScale": 1.0 }\n]',
		required: true,
		displayOptions: {
			show: {
				operation: ['multiSynthesis'],
				inputMode: ['json'],
			},
		},
		description: 'テキスト一覧のJSON配列。text のみ必須、他はすべてオプション（未指定時はベース設定→APIデフォルトを使用）',
		hint: '<div style="font-family:monospace;font-size:11px;line-height:1.4;white-space:pre;margin:4px 0">[\n  { "text": "テキスト1" },\n  {\n    "text":                "テキスト2",  <span style="color:#888">// テキスト（必須）</span>\n    "speakerId":           888753760,   <span style="color:#888">// 話者ID</span>\n    "speedScale":          1.0,         <span style="color:#888">// 話速 (0.5〜2.0)</span>\n    "pitchScale":          0.0,         <span style="color:#888">// 音高 (-0.15〜0.15)</span>\n    "intonationScale":     1.0,         <span style="color:#888">// 感情表現 (0.0〜2.0)</span>\n    "volumeScale":         1.0,         <span style="color:#888">// 音量 (0.0〜2.0)</span>\n    "prePhonemeLength":    0.1,         <span style="color:#888">// 開始無音 (0.0〜1.5秒)</span>\n    "postPhonemeLength":   0.1,         <span style="color:#888">// 終了無音 (0.0〜1.5秒)</span>\n    "pauseLength":         0.0,         <span style="color:#888">// 句読点無音 (0.0〜3.0秒)</span>\n    "tempoDynamicsScale":  1.0          <span style="color:#888">// テンポ緩急 (0.0〜2.0)</span>\n  }\n]</div>',
	},
	// AudioQueryパラメータ（音声合成簡略用オプション）
	{
		displayName: '音声設定: audioParams',
		name: 'audioParams',
		type: 'collection',
		default: {},
		placeholder: '設定を追加',
		displayOptions: {
			show: {
				operation: ['synthesize'],
			},
		},
		description: '音声のパラメータ設定。未設定の場合はAPIデフォルト値を使用',
		options: [
			{
				displayName: '話速: speedScale',
				name: 'speedScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.5, maxValue: 2.0, numberStepSize: 0.1 },
				description: '話す速さ（最小: 0.5、最大: 2.0、デフォルト: 1.0）',
			},
			{
				displayName: '音高: pitchScale',
				name: 'pitchScale',
				type: 'number',
				default: 0.0,
				typeOptions: { minValue: -0.15, maxValue: 0.15, numberStepSize: 0.01 },
				description: '声の高さ（最小: -0.15、最大: 0.15、デフォルト: 0.0）',
			},
			{
				displayName: '感情表現: intonationScale',
				name: 'intonationScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: '感情表現の強弱（最小: 0.0、最大: 2.0、デフォルト: 1.0）。話者スタイルに応じた感情の込め方を調整',
			},
			{
				displayName: '音量: volumeScale',
				name: 'volumeScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: '音量（最小: 0.0、最大: 2.0、デフォルト: 1.0）',
			},
			{
				displayName: '開始無音: prePhonemeLength',
				name: 'prePhonemeLength',
				type: 'number',
				default: 0.1,
				typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
				description: '音声開始前の無音の長さ（最小: 0.0秒、最大: 1.5秒、デフォルト: 0.1秒）',
			},
			{
				displayName: '終了無音: postPhonemeLength',
				name: 'postPhonemeLength',
				type: 'number',
				default: 0.1,
				typeOptions: { minValue: 0.0, maxValue: 1.5, numberStepSize: 0.1 },
				description: '音声終了後の無音の長さ（最小: 0.0秒、最大: 1.5秒、デフォルト: 0.1秒）',
			},
			{
				displayName: '句読点無音: pauseLength',
				name: 'pauseLength',
				type: 'number',
				default: 0.0,
				typeOptions: { minValue: 0.0, maxValue: 3.0, numberStepSize: 0.1 },
				description: '句読点などの無音時間（最小: 0.0秒、最大: 3.0秒）。未設定の場合はAPIデフォルト（null=自動）を使用',
			},
			{
				displayName: 'テンポ緩急: tempoDynamicsScale',
				name: 'tempoDynamicsScale',
				type: 'number',
				default: 1.0,
				typeOptions: { minValue: 0.0, maxValue: 2.0, numberStepSize: 0.1 },
				description: 'テンポの緩急の強弱（最小: 0.0、最大: 2.0、デフォルト: 1.0）。AivisSpeech固有',
			},
		],
	},
	{
		displayName: 'ステレオ出力: outputStereo',
		name: 'outputStereo',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				operation: ['synthesize', 'multiSynthesis'],
			},
		},
		description: 'ステレオ（2ch）で出力するか（デフォルト: モノラル）',
	},
	{
		displayName: 'AudioQuery (JSON): audioQueryJson',
		name: 'audioQueryJson',
		type: 'json',
		default: '',
		required: true,
		displayOptions: {
			show: {
				operation: ['synthesisFromQuery'],
			},
		},
		description: 'AudioQuery取得で得たJSONデータ',
	},
];
